# Window Manager
<WindowManager>:
    loading: loading
    register: register
    home: home
    view: view
    update: update
    nointernet: nointernet
    userguide: userguide
    LoadingPage:
        id: loading
    RegisterPage:
        id: register
    HomePage:
        id: home
    ViewDetailsPage:
        id: view
    UpdatePage:
        id: update
    NoInternet:
        id: nointernet
    UserGuide:
        id: userguide
